### ISSUE TITLE
Errors from tab.navigateTo() in Firefox versions > 56

### ISSUE THREAD

**Issue by autonome** [saucelabs/foxdriver#1]
tab.navigateTo() works fine in 56 (release channel) for me, but 57 (beta channel, currently) and 58 (nightly, currently) both give the same error:

Error: No such actor for ID: server1.conn1.child1/tab1 (noSuchActor)
    at /Users/dietrich/Dropbox/misc/quantum/node_modules/foxdriver/build/actor.js:61:23
    at Generator.next (<anonymous>)
    at step (/Users/dietrich/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/dietrich/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by autonome** [comment]
@christian-bromann Hi, any ideas on what's happening? I'm on a Mac, if that helps.

**Comment by autonome** [comment]
I implemented some retry logic around this and it so far it's worked 100% of the time on the immediately subsequent attempt.

**Comment by autonome** [comment]
Ok, not 100% of the time 😭

**Comment by christian-bromann** [comment]
Hey @autonome thanks for raising the issue. I unfortunately don't know why this is happening.

**Comment by captainbrosset** [comment]
I tested this on Windows 10 with Firefox 58 (now in beta) and didn't have any issue with running `tab.navigateTo` there.

I did however reproduce the error on macOS. So it is dependent on the OS somehow.

**Comment by captainbrosset** [comment]
Investigated a little bit more.

When I tested on Windows 10, I used `launch` but provided the path to a bin that was already running, so Windows did not open a new instance of Firefox, but instead `launch` acted like `attach`. And it worked there.

When I tested on macOS however, `launch` did really launch a new Firefox process, and it was failing there. I then tested with `attach` in order to attach to an already running instance of Firefox, and it worked fine.

My impression is that this is a timing issue. The result of `browser.tabs` after `launch` has run isn't correct I'm guessing. By the time I try to use `navigateTo` with the first tab for example it fails like @autonome described.
However, when I use `attach` and do the same with a tab from the `browser.tabs` list, then it works fine because those tabs actually do exist.

**Comment by captainbrosset** [comment]
Sorry. False alert. This isn't a macOS-only issue. I reproduced on Windows too by setting the port to something else. I already had a Firefox listening on 9222, and so, even if I was launching a new instance, OI was really connected to the other one. So, with a new port, I reproduce the issue on Windows too.

**Comment by christian-bromann** [comment]
@captainbrosset thanks for looking into it. With Firefox Quantum there might have been changes made to some of the actors.

**Comment by ksajxai** [comment]
With automatic testing with --headless Firefox in Docker container almost always gives

`Error: No such actor for ID: server1.conn1.child6/tab1 (noSuchActor)`

It can randomly give error or work correctly on restarting.

Are there any plans to fix this timing issue with tab creation?
